def nth_fibonacci_iterative(n: int, /): ...
def nth_fibonacci_recursive(n: int, /, *, f0: int = 0, f1: int = 1): ...
def nth_fibonacci_recursive_tail(n: int, /): ...

class Fibonacci:
    first_n: ...

    def __init__(self, first_n: int, /): ...
    def __iter__(self, /): ...

class FibonacciIterator:
    i: ...
    ith: ...
    next: ...
    stop: ...

    def __init__(self, i: int, ith: int, next: int, stop: int): ...
    def __next__(self): ...
